service:
  name: docs-api
  team: document
  namespace: document-dev

image:
  repository: ghcr.io/chku3401/docs-api
  tag: a0e6abe57bb82a3e79c78e0a569edbe9fa7995c7
  pullPolicy: IfNotPresent

replicaCount: 2

containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

readinessProbe:
  path: /health
  port: 8080

livenessProbe:
  path: /health
  port: 8080
