service:
  name: docs-api
  team: document
  namespace: document-dev

image:
  repository: ghcr.io/chku3401/docs-api
  tag: b09e8d0ea2c3a67a099d22750790ffd163f26721
  pullPolicy: IfNotPresent

replicaCount: 2

containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

readinessProbe:
  path: /health
  port: 8080

livenessProbe:
  path: /health
  port: 8080
