service:
  name: payment-api
  team: payments
  namespace: payments-dev

image:
  repository: ghcr.io/chku3401/payment-api
  tag: ff4a742f0a71dd472dd4cc24614993e622627363
  pullPolicy: IfNotPresent

replicaCount: 2

containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

readinessProbe:
  path: /health
  port: 8080

livenessProbe:
  path: /health
  port: 8080
