import re
import shutil
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = REPO_ROOT / "templates"
GENERATED_DIR = REPO_ROOT / "generated"
WORKFLOWS_DIR = REPO_ROOT / ".github" / "workflows"

VALID_LANGUAGES = {"java", "node"}
NAME_PATTERN = re.compile(r"^[a-z][a-z0-9-]{1,38}[a-z0-9]$")

_LANGUAGE_DIRS = {
    "java": "java-springboot",
    "node": "node-service",
}

_PLACEHOLDER_FILE_SUFFIXES = {
    ".json", ".js", ".xml", ".java", ".properties", ".md",
}


class ServiceGenerationError(ValueError):
    """Raised for invalid input (bad name/language/team/namespace)."""


class ServiceExistsError(FileExistsError):
    """Raised when the target service directory already exists."""


def validate_request(service_name: str, team: str, language: str, namespace: str) -> None:
    if language not in VALID_LANGUAGES:
        raise ServiceGenerationError(
            f"Unsupported language '{language}'. Must be one of: {sorted(VALID_LANGUAGES)}"
        )
    if not NAME_PATTERN.match(service_name):
        raise ServiceGenerationError(
            "service_name must be lowercase alphanumeric with hyphens, "
            "3-40 chars, and cannot start/end with a hyphen (e.g. 'payment-api')"
        )
    if not team or not re.match(r"^[a-z][a-z0-9-]*$", team):
        raise ServiceGenerationError("team must be a lowercase slug (e.g. 'payments')")
    if not namespace or not re.match(r"^[a-z][a-z0-9-]*$", namespace):
        raise ServiceGenerationError("namespace must be a lowercase slug (e.g. 'payments-dev')")


def _substitute(text: str, service_name: str, team: str) -> str:
    return text.replace("__SERVICE_NAME__", service_name).replace("__TEAM__", team)


def _copy_source_template(service_name: str, team: str, language: str, dest: Path) -> None:
    src = TEMPLATES_DIR / _LANGUAGE_DIRS[language]
    for path in src.rglob("*"):
        rel = path.relative_to(src)
        target = dest / rel
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        if path.suffix in _PLACEHOLDER_FILE_SUFFIXES:
            content = path.read_text()
            target.write_text(_substitute(content, service_name, team))
        else:
            shutil.copyfile(path, target)


_DOCKERFILE_JAVA = """FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
"""

_DOCKERFILE_NODE = """FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY . .
EXPOSE 8080
CMD ["npm", "start"]
"""

_CATALOG_INFO = """apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {service_name}
  description: {service_name} owned by {team}
spec:
  type: service
  lifecycle: experimental
  owner: {team}
"""

_SERVICE_README = """# {service_name}

Owner team: {team}
Namespace: {namespace}
Language: {language}

Generated by the IDP platform demo.

## Run locally

```bash
docker build -t {service_name}:local generated/{service_name}
docker run -p 8080:8080 {service_name}:local
curl localhost:8080/health
```
"""

_HELM_VALUES = """service:
  name: {service_name}
  team: {team}
  namespace: {namespace}

image:
  repository: {service_name}
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

readinessProbe:
  path: /health
  port: 8080

livenessProbe:
  path: /health
  port: 8080
"""

_CI_JAVA = """name: {service_name} CI

on:
  push:
    branches: [ main ]
    paths: [ 'generated/{service_name}/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'generated/{service_name}/**' ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: generated/{service_name}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Unit tests
        run: mvn -B test

      - name: Package
        run: mvn -B -DskipTests package

      - name: Build container image
        run: docker build -t {service_name}:${{{{ github.sha }}}} .

      - name: Scan container image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: {service_name}:${{{{ github.sha }}}}
          severity: CRITICAL,HIGH
          exit-code: '0'
"""

_CI_NODE = """name: {service_name} CI

on:
  push:
    branches: [ main ]
    paths: [ 'generated/{service_name}/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'generated/{service_name}/**' ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: generated/{service_name}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm test

      - name: Build container image
        run: docker build -t {service_name}:${{{{ github.sha }}}} .

      - name: Scan container image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: {service_name}:${{{{ github.sha }}}}
          severity: CRITICAL,HIGH
          exit-code: '0'
"""


def generate_service(
    service_name: str,
    team: str,
    language: str,
    namespace: str,
) -> dict:
    """Generate a full service scaffold. Returns a summary dict.

    Raises ServiceGenerationError for invalid input, ServiceExistsError if the
    target directory already exists.
    """
    validate_request(service_name, team, language, namespace)

    base = GENERATED_DIR / service_name
    if base.exists():
        raise ServiceExistsError(f"Service '{service_name}' already exists at {base}")

    fmt = dict(service_name=service_name, team=team, language=language, namespace=namespace)

    _copy_source_template(service_name, team, language, base)

    dockerfile = _DOCKERFILE_JAVA if language == "java" else _DOCKERFILE_NODE
    (base / "Dockerfile").write_text(dockerfile)
    (base / "catalog-info.yaml").write_text(_CATALOG_INFO.format(**fmt))
    (base / "README.md").write_text(_SERVICE_README.format(**fmt))

    helm_dir = base / "helm"
    helm_dir.mkdir(parents=True, exist_ok=True)
    (helm_dir / "values.yaml").write_text(_HELM_VALUES.format(**fmt))

    WORKFLOWS_DIR.mkdir(parents=True, exist_ok=True)
    ci_template = _CI_JAVA if language == "java" else _CI_NODE
    (WORKFLOWS_DIR / f"{service_name}.yaml").write_text(ci_template.format(**fmt))

    return {
        "service": service_name,
        "team": team,
        "namespace": namespace,
        "language": language,
        "path": str(base.relative_to(REPO_ROOT)),
        "generated_items": [
            "source template",
            "Dockerfile",
            "catalog-info.yaml",
            "helm/values.yaml",
            f".github/workflows/{service_name}.yaml",
        ],
    }


def list_services() -> list[dict]:
    if not GENERATED_DIR.exists():
        return []

    services = []
    for base in sorted(GENERATED_DIR.iterdir()):
        catalog_file = base / "catalog-info.yaml"
        values_file = base / "helm" / "values.yaml"
        if not base.is_dir() or not catalog_file.exists() or not values_file.exists():
            continue

        catalog = yaml.safe_load(catalog_file.read_text())
        values = yaml.safe_load(values_file.read_text())
        services.append({
            "service_name": base.name,
            "team": catalog["spec"]["owner"],
            "namespace": values["service"]["namespace"],
            "language": "java" if (base / "pom.xml").exists() else "node",
            "path": str(base.relative_to(REPO_ROOT)),
        })
    return services
